server:
  port: 8083

spring:
  application:
    name: cloud-file-server
  r2dbc:
    url: r2dbc:pool:mysql://localhost:55724/cloud_storage
    username: storage
    password: storage
  flyway:
    url: jdbc:mysql://localhost:55724/cloud_storage
    locations: classpath:db/migration
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: gluhov