server:
  port: 8083

spring:
  application:
    name: cloud-file-server
  cloud:
    aws:
      credentials:
        access-key: ${access-key}
        secret-key: ${secret-key}
      region:
        static: us-east-1
  r2dbc:
    url: r2dbc:pool:mysql://localhost:55724/cloud_storage
    username: storage
    password: storage
  flyway:
    url: jdbc:mysql://localhost:55724/cloud_storage
    locations: classpath:db/migration
s3:
  bucket: gluhov-file-storage
  region: us-east-1
jwt:
  password:
    encoder:
      secret: ${encoder-secret}
      iteration: 64
      keylength: 256
  secret: ${jwt-secret}
  expiration: 3600
  issuer: gluhov